return 213 + 321
return
213 + 321
return;
213 + 321
break
continue
yield 213 + 321
throw 213 + 321

do
print()
while (a)
a = 1 // Should be outside loop

while (a)
a = 1 // Should inside loop

try
print()
catch (a)
print()

try {} catch (a) {}
try ; catch (a) ;